apiVersion: v1
kind: Service
metadata:
  name: {{ include "leantime.fullname" . }}
  labels:
    {{- include "leantime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      targetPort: http
      port: {{ .Values.service.port }}
  selector:
    {{- include "leantime.selectorLabels" . | nindent 4 }}
